name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Download kernel tree
        run: git clone https://github.com/Gamesmes90/android_kernel_oneplus_sm8350.git

      - name: Initialize Kernel SU Next SUSFS
        run: |
          cd android_kernel_oneplus_sm8350
          bash init_ksu.sh susfs
          cd ..

      - name: Downloade Lineage OS build
        run: bash build.sh lemonadep
      
      - name: Setup and build
        run: |
          source .github/workflows/versioning

          # This check is to avoid uploading to the same tag if there happens to be multiple builds in one day
          # Initialize variables
          NEW_VERSION="$VERSION"
          TAG="$NEW_VERSION-$ANDROID_VERSION-$DATE"
          COUNTER=1
          
          # Query the remote repo. Loop and update NEW_VERSION and TAG if it already exists.
          while git ls-remote --tags "https://${{ secrets.TOKEN }}@github.com/Gamesmes90/android_kernel_oneplus_sm8350.git" "refs/tags/$TAG" | grep -q "refs/tags/$TAG"; do
            NEW_VERSION="${VERSION}-${COUNTER}"
            TAG="$NEW_VERSION-$ANDROID_VERSION-$DATE"
            COUNTER=$((COUNTER + 1))
          done
          
          echo "Available tag generated: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          
          # Update the VERSION variable in the file
          sed -i "s/^VERSION=.*/VERSION=$NEW_VERSION/" .github/workflows/versioning

          echo "TAG=$VERSION-$ANDROID_VERSION-$DATE" >> $GITHUB_ENV
          bash build.sh
          mv build/kernel-oneplus-sm8350.zip build/kernel-oneplus-sm8350-${TAG}.zip

      - name: Generate Changelog
        run: |
          cd android_kernel_oneplus_sm8350
          bash .github/generate_changelog.sh

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          repository: Gamesmes90/android_kernel_oneplus_sm8350
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          files: build/kernel-oneplus-sm8350-${{ env.TAG }}.zip
          body_path: android_kernel_oneplus_sm8350/.github/release_notes.txt
          token: ${{ secrets.TOKEN }}
